version: "3.9"

services:
  fastapi_app:
    image: ghcr.io/phmasc/fastapi-downloadyt:0.1.3
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    ports:
      - "8000:8000"
    networks:
      - network_swarm_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
        failure_action: rollback

networks:
  network_swarm_public:
    external: true
